#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          irclogger-viewer
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: irclogger viewer bot
### END INIT INFO

# Author: whitequark <whitequark@whitequark.org>

ROOT=/var/www/irclog
START_ARGS="--chuid irclog"

DESC="irclogger viewer"
DAEMON=/usr/bin/thin
DAEMON_ARGS="-c ${ROOT} -C ${ROOT}/config/thin.yml start"
PIDFILE=${ROOT}/tmp/viewer.pid

do_stop_cmd() {
  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
      --pidfile ${PIDFILE} --name $NAME
}
